; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Fri Jul 03 2020 20:35:09 GMT+0200 (Midden-Europese zomertijd)
M561 ; clear any bed transform
G29 S2; Clear bed height map
G30 P0 X-175 Y0 Z-99999    ; probe near a leadscrew left
G30 P1 X175  Y0 Z-99999 S2 ; probe near a leadscrew right
G29 S1 